/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#181d26',
        'primary-active': '#0d1218',
        ink: '#181d26',
        body: '#333840',
        muted: '#41454d',
        hairline: '#dddddd',
        'border-strong': '#9297a0',
        canvas: '#ffffff',
        'surface-soft': '#f8fafc',
        'surface-strong': '#e0e2e6',
        'surface-dark': '#181d26',
        'surface-dark-elevated': '#1d1f25',
        'signature-coral': '#aa2d00',
        'signature-forest': '#0a2e0e',
        'signature-cream': '#f5e9d4',
        'signature-peach': '#fcab79',
        'signature-mint': '#a8d8c4',
        'signature-yellow': '#f4d35e',
        'signature-mustard': '#d9a441',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        link: '#1b61c9',
        'link-active': '#1a3866',
        info: '#254fad',
        'info-border': '#458fff',
        success: '#006400',
        'success-border': '#39bf45',
        'pricing-ink': '#1d1f25',

        // Legacy aliases used by the shared component layer.
        'soft-stone': '#f8fafc',
        'canvas-parchment': '#f8fafc',
        'surface-pearl': '#ffffff',
        'canvas-night': '#181d26',
        'dark-gray': '#181d26',
        'cohere-black': '#181d26',
        'dark-navy': '#181d26',
        'medium-gray': '#41454d',
        slate: '#41454d',
        'body-muted': '#41454d',
        'ink-muted-80': '#41454d',
        'ink-muted-48': '#41454d',
        'border-light': '#dddddd',
        'card-border': '#dddddd',
        'divider-soft': '#dddddd',
        'light-gray': '#ffffff',
        'accent-blue': '#1b61c9',
        'action-blue': '#1b61c9',
        'focus-blue': '#458fff',
        'form-focus': '#458fff',
        'deep-green': '#0a2e0e',
        'pale-green': '#a8d8c4',
        'pale-blue': '#f8fafc',
        coral: '#aa2d00',
        'coral-soft': '#fcab79',
        error: '#aa2d00',
      },
      fontFamily: {
        display: ['Haas Groot Disp', 'Haas', 'Inter', 'system-ui', 'sans-serif'],
        sans: ['Haas', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Haas', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '0', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '400' }],
        'display-md': ['32px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '400' }],
        'section-heading': ['32px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '400' }],
        'card-heading': ['24px', { lineHeight: '1.35', letterSpacing: '0.12px', fontWeight: '400' }],
        'feature-heading': ['20px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-large': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        body: ['14px', { lineHeight: '1.25', letterSpacing: '0', fontWeight: '400' }],
        button: ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        caption: ['14px', { lineHeight: '1.35', letterSpacing: '0.16px', fontWeight: '500' }],
        'mono-label': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        micro: ['13.12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '600' }],
      },
      borderRadius: {
        xs: '2px',
        sm: '6px',
        md: '10px',
        lg: '12px',
        xl: '12px',
        '2xl': '12px',
        '3xl': '12px',
        pill: '9999px',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(24, 29, 38, 0.06)',
        modal: '0 12px 32px -12px rgba(24, 29, 38, 0.16)',
        'card-hover': '0 4px 12px rgba(24, 29, 38, 0.08)',
      },
      animation: {},
    },
  },
  plugins: [],
}
